OUT=../../stylesheets/icon-font

copy:
	mkdir -p ${OUT}
	cp css/custom.eot ${OUT}
	cp css/custom.svg ${OUT}
	cp css/custom.woff ${OUT}
	cp css/custom.ttf ${OUT}
	cp css/custom.css ${OUT}/icon-font.css
